# Generated by Django 3.1.2 on 2021-03-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
