# Generated by Django 3.1.2 on 2021-03-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
