# Generated by Django 3.1.2 on 2021-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_book',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='property_book',
            name='date_to',
            field=models.DateField(),
        ),
    ]
