# Generated by Django 3.1.2 on 2021-09-04 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210904_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_book',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='property_book',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
